FROM node:20-alpine

WORKDIR /app

COPY ./lenny/lenny_Front_end/package.json /app/
COPY ./lenny/lenny_Front_end/vite.config.ts /app/
COPY ./lenny/lenny_Front_end/ /app/lenny/lenny_Front_end/

WORKDIR /app/lenny/lenny_Front_end

RUN npm install

EXPOSE 8080

CMD ["npm", "run", "dev"]